-- SELECT ROUND(AVG(amount), 2) FROM payment;
-- SELECT MIN(amount) FROM payment;
-- SELECT COUNT(amount) FROM payment ORDER BY amount;
-- SELECT COUNT(amount) FROM payment WHERE amount=0.00;
-- SELECT MAX(amount) FROM payment;
-- SELECT SUM(amount) FROM payment;
